name: Update Repo Permissions

on:
  push:
    branches:
      - main

jobs:
  update-permissions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Create Repo Envs
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.MY_PAT }}
          script: |
            const createEnvs = async () => {
              await github.rest.repos.createOrUpdateEnvironment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                environment_name: 'dev1'
              });

              await github.rest.repos.createOrUpdateEnvironment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                environment_name: 'qa1'
              });

              await github.rest.repos.createOrUpdateEnvironment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                environment_name: 'sandbox'
              });
            };
            createEnvs();

      - name: Create Repo Branch Protection
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.MY_PAT }}
          script: |
            const updateBranchProtection = async () => {
              await github.rest.repos.updateBranchProtection({
                owner: context.repo.owner,
                repo: context.repo.repo,
                branch: 'main',
                required_status_checks: null,
                enforce_admins: false,
                required_pull_request_reviews: null
              });
            }

            updateBranchProtection();
